const LEGAL={brand:'RIVAYAT',operator:'RIVAYAT',businessAddress:'',privacyEmail:'support@rivayat.in',email:'support@rivayat.in',supportPhone:'',grievanceOfficer:'',grievanceEmail:'support@rivayat.in',gstin:'',returnDays:7,updated:'17 August 2026'};
async function loadLegalSettings(){try{const d=await api('/launch/legal-settings'),x=d.settings||{};Object.assign(LEGAL,x);LEGAL.email=LEGAL.privacyEmail||LEGAL.email;LEGAL.updated=x.updatedAt?new Date(x.updatedAt).toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'}):LEGAL.updated}catch{}}
function legalIdentity(){return `<div class="legal-identity"><strong>${esc(LEGAL.operator||LEGAL.brand)}</strong>${LEGAL.businessAddress?`<span>${esc(LEGAL.businessAddress)}</span>`:''}${LEGAL.gstin?`<span>GSTIN: ${esc(LEGAL.gstin)}</span>`:''}${LEGAL.supportPhone?`<span>Phone: ${esc(LEGAL.supportPhone)}</span>`:''}${LEGAL.grievanceOfficer?`<span>Grievance contact: ${esc(LEGAL.grievanceOfficer)} · ${esc(LEGAL.grievanceEmail||LEGAL.email)}</span>`:''}</div>`}
function legalNav(active){return `<nav class="policy-nav">${[['privacy','Privacy'],['terms','Terms'],['returns-policy','Returns'],['shipping','Shipping'],['cookies','Cookies']].map(([k,n])=>`<a class="${active===k?'active':''}" href="#/${k}">${n}</a>`).join('')}</nav>`}
function sec(t,h){return `<section><h2>${t}</h2>${h}</section>`}
function legalPage(kind){const p={privacy:privacyPolicy(),terms:termsPolicy(),'returns-policy':returnsPolicy(),shipping:shippingPolicy(),cookies:cookiesPolicy()}[kind];return `<div class="page policy-page"><div class="shell policy-shell"><header class="policy-header"><span class="eyebrow">RIVAYAT / Customer trust</span><h1>${p.title}</h1><p>${p.intro}</p><div class="policy-meta">Last updated ${LEGAL.updated} · <a href="mailto:${LEGAL.email}">${LEGAL.email}</a></div>${legalIdentity()}${legalNav(kind)}</header><article class="policy-document">${p.body}</article></div></div>`}
function privacyPolicy(){return {title:'Privacy Policy',intro:'What we collect, why we use it, who receives it and the choices available to you.',body:
sec('Who is responsible',`<p>${esc(LEGAL.operator||'RIVAYAT')} operates RIVAYAT. Contact <a href="mailto:${esc(LEGAL.privacyEmail||LEGAL.email)}">${esc(LEGAL.privacyEmail||LEGAL.email)}</a> for privacy requests.</p>`)+
sec('Information we process',`<p>Depending on your use of RIVAYAT, we may process your name, verified email, phone number, delivery addresses, order/return history, account authentication information, saved preferences, customer-support communications and a profile photo if you add one. Google sign-in may provide your name, verified email and Google profile picture. Payment credentials are intended to be processed by the payment provider rather than stored by RIVAYAT.</p>`)+
sec('Purposes',`<ul><li>create and secure accounts;</li><li>process, deliver and support orders and returns;</li><li>send verification, security and transactional order emails;</li><li>save addresses and preferences you request;</li><li>prevent abuse, fraud and security incidents;</li><li>meet tax, accounting, consumer-protection and legal obligations;</li><li>send marketing only where permitted and appropriately authorised.</li></ul>`)+
sec('Legal basis and consent',`<p>Processing is carried out for lawful purposes. Where consent is required, it should be specific and capable of withdrawal. Where laws such as the GDPR apply, processing may also rely on contract, legal obligation or legitimate interests as permitted by law. Under India’s data-protection framework, notices, consent and statutory rights apply according to the provisions in force.</p>`)+
sec('Service providers and transfers',`<p>We may share the minimum information needed with hosting/database, email, Google authentication, payment, delivery/logistics, security and professional service providers. Some providers may process data outside your country; where transfer restrictions apply, an available lawful safeguard should be used. The current storefront is not designed to sell personal data or share it for cross-context behavioural advertising.</p>`)+
sec('Retention',`<p>Profile information is kept while an account is active and as otherwise needed for stated purposes. Order, invoice, payment, dispute and fraud-prevention records may be retained longer for legal, tax, accounting, chargeback or claims requirements. Verification codes expire automatically.</p>`)+
sec('Your rights',`<p>Rights depend on your location and the law that applies. They may include access, correction, deletion/erasure, withdrawal of consent, objection or restriction, data portability, grievance redressal, and complaint to a competent authority. California residents may also have applicable rights to know, delete, correct, opt out of sale/sharing, limit certain uses of sensitive personal information and receive non-discriminatory treatment. RIVAYAT currently states that it does not sell personal data.</p><p>You can request account deletion under <strong>Profile → Security & privacy</strong> or contact ${esc(LEGAL.privacyEmail||LEGAL.email)}. Identity verification may be required.</p>`)+
sec('Account deletion',`<p>Deleting your account removes the active login profile and saved account data. Transaction records may remain when necessary for legal compliance, accounting, fraud prevention, dispute resolution or legal claims.</p>`)+
sec('Children and security',`<p>RIVAYAT is intended for customers able to enter into purchase contracts. We do not intentionally design the service to profile children. Security measures include password hashing, short-lived verification codes, authenticated admin controls and HTTPS when the site is correctly deployed. No online service can guarantee absolute security.</p>`)+
sec('Complaints and changes',`<p>We may update this policy when services or obligations change. For a grievance, contact ${esc(LEGAL.grievanceOfficer||'the RIVAYAT grievance contact')} at <a href="mailto:${esc(LEGAL.grievanceEmail||LEGAL.email)}">${esc(LEGAL.grievanceEmail||LEGAL.email)}</a>. You may also contact the relevant data-protection or consumer authority where applicable.</p>`)}}
function termsPolicy(){return {title:'Terms of Use & Sale',intro:'Clear purchase terms that sit alongside, not instead of, mandatory consumer rights.',body:sec('Store operator',`<p>These terms apply to purchases from ${esc(LEGAL.operator||'RIVAYAT')}, trading as RIVAYAT. Contact ${esc(LEGAL.email)}.</p>`)+sec('Products and pricing',`<p>We aim to describe products, sizing, colours, prices and availability accurately. Screen/photography differences may occur. Checkout shows the applicable price, discount, tax and delivery charge before confirmation. Mandatory rights for materially incorrect or non-conforming goods remain unaffected.</p>`)+sec('Orders and payment',`<p>Submitting checkout is an offer to purchase. Acceptance is subject to stock, payment checks, delivery feasibility and fraud controls. If an accepted paid order cannot be fulfilled, the applicable refund will be initiated. Payment providers may impose separate terms.</p>`)+sec('Delivery and updates',`<p>Delivery dates are estimates unless applicable law requires otherwise. We send major order-status updates to the email supplied with the order.</p>`)+sec('Returns and cancellations',`<p>Our <a href="#/returns-policy">Returns & Refund Policy</a> forms part of these terms. Nothing here removes a right that cannot legally be waived.</p>`)+sec('Accounts and acceptable use',`<p>Keep access to your email and account secure. Email login codes are short-lived and must not be shared. Do not misuse the service, interfere with security or use another person’s account without authority.</p>`)+sec('Liability and governing rights',`<p>Nothing excludes liability that cannot be excluded by law. These terms operate alongside applicable consumer law, including mandatory protections in a customer’s jurisdiction.</p>`)} }
function returnsPolicy(){return {title:'Returns, Refunds & Cancellation',intro:'A straightforward process for cancellations and eligible returns.',body:sec('Cancellation',`<p>You may request cancellation while an order is still eligible before dispatch. After shipment, use the return process where available.</p>`)+sec('Damaged, defective or incorrect items',`<p>Contact ${esc(LEGAL.email)} as soon as reasonably possible after delivery with your order number and evidence where relevant. RIVAYAT will provide the remedy required by applicable law and the circumstances.</p>`)+sec('Change-of-mind returns',`<p>For eligible apparel, request a return within ${Number(LEGAL.returnDays||7)} calendar days of delivery. Items should generally be unworn, unwashed and returned with original tags/packaging, except where inspection is reasonably necessary or law provides otherwise. Clearly disclosed hygiene-sensitive, customised or final-sale items may be excluded where lawful.</p>`)+sec('Refunds',`<p>Approved refunds are initiated after receipt/inspection or earlier where required by law. Bank or payment-provider settlement times are outside RIVAYAT’s direct control. COD refunds may require verified payout details.</p>`)+sec('Statutory rights',`<p>This policy does not reduce mandatory remedies for defective, misdescribed or non-conforming goods.</p>`)} }
function shippingPolicy(){return {title:'Shipping Policy',intro:'What happens from checkout to delivery.',body:sec('Processing',`<p>Orders are checked for stock and delivery details before fulfilment. Statuses may include Pending, Confirmed, Packed, Shipped, Out for Delivery and Delivered.</p>`)+sec('Charges and address',`<p>The final delivery charge is shown at checkout. Please provide a complete address, reachable phone number and correct postal code.</p>`)+sec('Delays',`<p>Carrier disruption, weather, public events and remote-area constraints can affect estimates. Contact ${esc(LEGAL.email)} if tracking appears stalled.</p>`)} }
function cookiesPolicy(){return {title:'Cookies & Local Storage',intro:'How browser storage is used to make RIVAYAT work.',body:sec('Essential storage',`<p>Browser storage is used for requested functions such as cart contents, theme, sign-in state and privacy preferences.</p>`)+sec('Optional technologies',`<p>Optional analytics or marketing technologies should remain off until a required consent or other lawful basis is available. Google sign-in is loaded when needed for authentication.</p>`)+sec('Your choice',`<p>You can review your preference below. Blocking essential storage may prevent cart or account functions from working.</p><button class="btn btn-secondary" onclick="resetPrivacyChoice()">Review privacy choices</button>`)} }
function ensurePrivacyBanner(){if(localStorage.getItem('rivayat_privacy_choice'))return;if(navigator.globalPrivacyControl===true){localStorage.setItem('rivayat_privacy_choice','essential');return}const e=document.createElement('div');e.id='privacyBanner';e.className='privacy-banner';e.innerHTML=`<div><strong>Your privacy, in plain English.</strong><p>Essential storage keeps the cart, account and security features working. Optional analytics/marketing stay off unless you allow them.</p><a href="#/privacy">Privacy policy</a></div><div><button class="btn btn-secondary" onclick="setPrivacyChoice('essential')">Essential only</button><button class="btn btn-primary" onclick="setPrivacyChoice('optional')">Allow optional</button></div>`;document.body.appendChild(e)}
function setPrivacyChoice(v){localStorage.setItem('rivayat_privacy_choice',v);document.getElementById('privacyBanner')?.remove();toast('Privacy preference saved','ok')}
function resetPrivacyChoice(){localStorage.removeItem('rivayat_privacy_choice');ensurePrivacyBanner()}
