const API=location.protocol==='file:'?'http://localhost:3000':'';let PRODUCTS=[],USER=JSON.parse(localStorage.getItem('rivayat_user')||'null'),CART=JSON.parse(localStorage.getItem('rivayat_cart')||'[]'),HOME={};let SELECTED_SIZE='';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function media(image,alt='',cls='',priority=false){if(String(image).startsWith('sprite:')){const [c,r]=image.slice(7).split(',').map(Number);return `<div class="sprite-media ${cls}" role="img" aria-label="${esc(alt)}" style="background-position:${c*25}% ${r*25}%"></div>`}const loading=priority?'loading="eager" fetchpriority="high"':'loading="lazy"';return `<img class="catalog-image ${cls}" src="${esc(image||'')}" alt="${esc(alt)}" ${loading} decoding="async">`}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(USER?.token)headers.Authorization='Bearer '+USER.token;const r=await fetch(API+path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false){const e=new Error(d.message||`Request failed (${r.status})`);e.data=d;throw e}return d}
function toast(msg,type=''){const e=document.createElement('div');e.className='toast '+type;e.textContent=msg;$('#toasts').append(e);setTimeout(()=>e.remove(),3200)}
function saveCart(){localStorage.setItem('rivayat_cart',JSON.stringify(CART));renderCounts()}
function renderCounts(){const n=CART.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=n;$('#mobileCartCount').textContent=n||''}
async function loadData(){try{PRODUCTS=await fetch('/catalog-2026.json').then(r=>r.json())}catch{}try{const d=await api('/products');const by=new Map(PRODUCTS.map(p=>[p.id,p]));PRODUCTS=(d.products||[]).map(p=>({...by.get(p.id),...p,image:p.image||by.get(p.id)?.image})).filter(p=>p.active!==false)}catch{}try{HOME=(await api('/settings/homepage')).settings||{}}catch{}}
function card(p){return `<article class="product-card"><a href="#/product/${esc(p.slug)}"><div class="product-media">${media(p.image,p.name)}<span class="product-pill">${esc(p.badge||'NEW')}</span></div><div class="product-info"><div class="product-name">${esc(p.name)}</div><div class="product-meta"><span>${esc(p.color||p.category)}</span><span class="price">${money(p.price)} ${p.mrp>p.price?`<span class="old-price">${money(p.mrp)}</span>`:''}</span></div></div></a><button class="quick-add" onclick="event.stopPropagation();quickAdd('${esc(p.id)}')">+</button></article>`}
function findP(v){return PRODUCTS.find(p=>p.id===v||p.slug===v)}
function homePage(){const f=PRODUCTS.slice(0,8),hood=findP('rose-static-panel-hoodie'),cargo=findP('field-olive-utility-cargo'),jack=findP('flame-track-jacket'),shirt=findP('emerald-check-overshirt'),hero=findP('charcoal-city-wide-cargo');return `<div class="page"><section class="hero"><div class="shell"><div class="hero-grid"><div class="hero-media">${media(hero?.image,'RIVAYAT streetwear','',true)}</div><div class="hero-copy"><span class="eyebrow">${esc(HOME.heroPill||'DROP 02 · 2026')}</span><h1>${esc(HOME.heroTitle||'Built for the next rotation.')}</h1><p>${esc(HOME.heroSubtitle||'Sharper silhouettes, graphic layers and utility-led cargos. A focused streetwear drop designed to mix, layer and repeat.')}</p><div class="cta-row"><a class="btn btn-primary" href="#/shop">Shop Drop 02 →</a><a class="btn btn-ghost" href="#/shop?cat=Cargos">Explore cargos</a></div></div></div></div></section><section class="section"><div class="shell"><div class="section-head"><div><span class="eyebrow">New rotation</span><h2>Just dropped.</h2></div><p>A curated edit instead of an endless feed. Open a piece, understand it, move with intent.</p></div><div class="product-rail">${f.map(card).join('')}</div></div></section><section class="section"><div class="shell"><div class="section-head"><div><span class="eyebrow">Shop by mood</span><h2>Find your lane.</h2></div></div><div class="category-grid">${[['Hoodies',hood],['Cargos',cargo],['Jackets',jack],['Shirts',shirt]].map(([n,p])=>`<a class="category-card" href="#/shop?cat=${n}">${media(p?.image,n)}<div class="category-copy"><span>RIVAYAT / ${n.toUpperCase()}</span><h3>${n}</h3></div></a>`).join('')}</div></div></section><section class="section"><div class="shell"><div class="editorial"><div class="editorial-copy"><span class="eyebrow">CITY UNIT</span><h2>Less scroll. More intent.</h2><p>Collections are grouped into clear routes so the store feels like a lookbook, not a never-ending product dump.</p><a class="btn btn-accent" href="#/shop?cat=Cargos">Shop utility →</a></div><div class="editorial-media">${media(findP('black-noir-utility-cargo')?.image,'Utility cargo')}</div></div></div></section><section class="section"><div class="shell"><div class="trust-strip"><div class="trust-item"><strong>Free shipping</strong><span>Above ₹999</span></div><div class="trust-item"><strong>Easy returns</strong><span>From your account</span></div><div class="trust-item"><strong>Secure login</strong><span>Email code + Google</span></div><div class="trust-item"><strong>Order tracking</strong><span>Live account status</span></div></div></div></section><section class="section"><div class="shell"><div class="newsletter"><h2>Get first access.</h2><form onsubmit="subscribe(event)"><input class="input" name="email" type="email" required placeholder="Email address"><button class="btn btn-accent">Join the list →</button></form></div></div></section></div>`}
function shopPage(params){let cat=params.get('cat')||'All',sort=params.get('sort')||'featured';let rows=PRODUCTS.filter(p=>cat==='All'||p.category===cat);if(sort==='low')rows.sort((a,b)=>a.price-b.price);if(sort==='high')rows.sort((a,b)=>b.price-a.price);const cats=['All','Hoodies','Cargos','Jackets','Shirts'];return `<div class="page"><div class="shell"><div class="shop-hero"><span class="eyebrow">RIVAYAT / SHOP</span><h1>${cat==='All'?'New Drop':esc(cat)}</h1><p class="muted">${rows.length} pieces · Built as a tight wardrobe, not an endless catalogue.</p></div><div class="filter-bar">${cats.map(c=>`<button class="filter-chip ${c===cat?'active':''}" onclick="location.hash='#/shop${c==='All'?'':'?cat='+c}'">${c}</button>`).join('')}<select class="select" onchange="location.hash='#/shop?${cat!=='All'?'cat='+cat+'&':''}sort='+this.value"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><div class="product-grid">${rows.map(card).join('')}</div></div></div>`}
function productPage(slug){const p=findP(slug);if(!p)return notFound();SELECTED_SIZE=p.sizes?.[0]||'M';return `<div class="page product-page"><div class="shell product-layout"><div class="product-gallery"><div class="product-main-image">${media(p.image,p.name,'',true)}</div></div><div class="product-detail"><span class="eyebrow">${esc(p.badge||p.category)}</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.description||'Official RIVAYAT piece.')}</p><h2>${money(p.price)} ${p.mrp>p.price?`<span class="old-price">${money(p.mrp)}</span>`:''}</h2><div class="field"><label>Choose size</label><div class="size-grid">${(p.sizes||['S','M','L','XL']).map((s,i)=>`<button class="size-btn ${i===0?'active':''}" onclick="chooseSize(this,'${esc(s)}')">${esc(s)}</button>`).join('')}</div></div><button class="btn btn-primary full" onclick="addToCart('${esc(p.id)}',SELECTED_SIZE)">Add to bag →</button><div class="panel" style="margin-top:18px"><strong>Details</strong><p class="muted">${(p.details||[]).map(esc).join(' · ')}</p><strong>Delivery</strong><p class="muted">Free shipping above ₹999. Returns can be requested from your account.</p></div></div></div></div>`}
function chooseSize(btn,s){SELECTED_SIZE=s;btn.parentElement.querySelectorAll('.size-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function quickAdd(id){const p=findP(id);addToCart(id,p?.sizes?.[0]||'M')}
function addToCart(id,size){const p=findP(id);if(!p)return;const key=id+'-'+size,x=CART.find(i=>i.key===key);if(x)x.qty++;else CART.push({key,id,name:p.name,size,qty:1,price:p.price,image:p.image});saveCart();toast('Added to your bag','ok');openCart()}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');document.body.style.overflow='hidden'}function closeCart(){$('#cartDrawer').classList.remove('open');document.body.style.overflow=''}function cartBackdrop(e){if(e.target.id==='cartDrawer')closeCart()}
function renderCart(){const box=$('#cartLines');if(!CART.length){box.innerHTML='<div class="empty">Your bag is empty.</div>';$('#cartDrawerSummary').innerHTML='';return}box.innerHTML=CART.map(x=>`<div class="cart-line">${media(x.image,x.name)}<div><strong>${esc(x.name)}</strong><div class="muted">Size ${esc(x.size)} · Qty ${x.qty}</div></div><div><strong>${money(x.price*x.qty)}</strong><br><button class="small-btn danger" onclick="removeCart('${esc(x.key)}')">Remove</button></div></div>`).join('');const sub=CART.reduce((s,x)=>s+x.price*x.qty,0);$('#cartDrawerSummary').innerHTML=`<div class="panel"><div class="summary-row"><span>Subtotal</span><strong>${money(sub)}</strong></div><div class="summary-row"><span>Shipping</span><span>${sub>=999?'Free':'Calculated at checkout'}</span></div><a class="btn btn-primary full" href="#/cart" onclick="closeCart()">Checkout →</a></div>`}
function removeCart(k){CART=CART.filter(x=>x.key!==k);saveCart();renderCart()}
async function subscribe(e){e.preventDefault();try{await api('/newsletter',{method:'POST',body:JSON.stringify({email:new FormData(e.currentTarget).get('email'),source:'Homepage 2026'})});e.currentTarget.reset();toast('You are on the list','ok')}catch(x){toast(x.message,'error')}}
function openSearch(){$('#searchOverlay').classList.add('open');$('#searchInput').focus();searchProducts('')}function closeSearch(){$('#searchOverlay').classList.remove('open')}function searchProducts(q){const rows=PRODUCTS.filter(p=>`${p.name} ${p.category} ${p.color}`.toLowerCase().includes(q.toLowerCase())).slice(0,9);$('#searchResults').innerHTML=rows.map(p=>`<a class="search-card" href="#/product/${p.slug}" onclick="closeSearch()">${media(p.image,p.name)}<div><strong>${esc(p.name)}</strong><div class="muted">${money(p.price)}</div></div></a>`).join('')}
$('#searchInput').addEventListener('input',e=>searchProducts(e.target.value));function notFound(){return `<div class="section"><div class="shell"><div class="panel"><h2>That page moved.</h2><a class="btn btn-primary" href="#/shop">Shop the drop</a></div></div></div>`}
