let AUTH_MODE='login',VERIFY_EMAIL='',VERIFY_KIND='signup',OTP_WAIT=0;
function saveUser(u){USER=u;localStorage.setItem('rivayat_user',JSON.stringify(u))}function logout(){USER=null;localStorage.removeItem('rivayat_user');toast('Signed out');location.hash='#/'}function goAccount(){location.hash=USER?(USER.role==='admin'?'#/admin':'#/profile'):'#/login'}
function loginPage(params){AUTH_MODE=params.get('mode')||AUTH_MODE;const visual=findP('rose-static-panel-hoodie');return `<div class="page auth-wrap"><div class="shell"><div class="auth-card"><aside class="auth-visual">${media(visual?.image,'RIVAYAT streetwear')}<span class="brand">RIVAYAT</span><div><span class="eyebrow">Your rotation, remembered</span><h2>Sign in. Pick up where you left off.</h2></div></aside><section class="auth-panel"><span class="eyebrow">RIVAYAT account</span><h1>${AUTH_MODE==='signup'?'Create your account.':AUTH_MODE==='otp'?'Sign in with a code.':'Welcome back.'}</h1><p class="muted">${AUTH_MODE==='signup'?'Save addresses, track orders and get early drop access.':AUTH_MODE==='otp'?'No password needed. We will email a 4-digit code.':'Track orders, save details and check out faster.'}</p><div class="auth-tabs"><button class="auth-tab ${AUTH_MODE==='login'?'active':''}" onclick="authMode('login')">Sign in</button><button class="auth-tab ${AUTH_MODE==='signup'?'active':''}" onclick="authMode('signup')">Create</button><button class="auth-tab ${AUTH_MODE==='otp'?'active':''}" onclick="authMode('otp')">Email code</button></div>${AUTH_MODE==='login'?loginForm():AUTH_MODE==='signup'?signupForm():otpForm()}</section></div></div></div>`}
function authMode(m){AUTH_MODE=m;location.hash='#/login?mode='+m}
function loginForm(){return `<form onsubmit="login(event)"><div class="field"><label>Email or username</label><input class="input" name="identifier" required autocomplete="username" placeholder="you@example.com"></div><div class="field"><label>Password</label><div class="input-wrap"><input class="input" id="loginPass" name="password" type="password" required autocomplete="current-password"><button class="password-toggle" type="button" onclick="togglePass('loginPass',this)">Show</button></div></div><div style="text-align:right;margin-bottom:12px"><button type="button" class="small-btn" onclick="forgotPassword()">Forgot password?</button></div><button class="btn btn-primary full">Sign in →</button><div id="googleButton" style="margin-top:12px"></div></form>`}
function signupForm(){return `<form onsubmit="signup(event)"><div class="form-row"><div class="field"><label>Name</label><input class="input" name="name" required autocomplete="name"></div><div class="field"><label>Phone</label><input class="input" name="phone" autocomplete="tel"></div></div><div class="field"><label>Email</label><input class="input" name="email" type="email" required autocomplete="email"></div><div class="field"><label>Password</label><div class="input-wrap"><input class="input" id="signupPass" name="password" type="password" minlength="8" required autocomplete="new-password"><button class="password-toggle" type="button" onclick="togglePass('signupPass',this)">Show</button></div><div class="form-note">At least 8 characters.</div></div><button class="btn btn-primary full">Create account →</button></form>`}
function otpForm(){return `<form onsubmit="requestOtp(event)"><div class="field"><label>Email</label><input class="input" name="email" type="email" required autocomplete="email" placeholder="you@example.com"></div><button class="btn btn-primary full">Send 4-digit code →</button><p class="form-note">Works for existing verified accounts.</p></form>`}
function togglePass(id,b){const i=document.getElementById(id);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'}
async function login(e){e.preventDefault();const b=e.currentTarget.querySelector('.btn-primary');b.disabled=true;try{const d=await api('/login-v2',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});saveUser(d.user);toast('Welcome back','ok');location.hash=d.user.role==='admin'?'#/admin':'#/profile'}catch(x){if(x.data?.requiresVerification){VERIFY_EMAIL=x.data.email;VERIFY_KIND='signup';showOtp()}else toast(x.message,'error');b.disabled=false}}
async function signup(e){e.preventDefault();try{const d=await api('/signup-v2',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});VERIFY_EMAIL=d.email;VERIFY_KIND='signup';showOtp();toast('4-digit code sent','ok')}catch(x){toast(x.message,'error')}}
async function requestOtp(e){e.preventDefault();const email=new FormData(e.currentTarget).get('email');try{await api('/auth/email-otp/request',{method:'POST',body:JSON.stringify({email})});VERIFY_EMAIL=email;VERIFY_KIND='login';showOtp();toast('If the account exists, a code was sent','ok')}catch(x){toast(x.message,'error')}}
function showOtp(){const m=$('#modal');m.innerHTML=`<div class="modal-head"><span class="brand">RIVAYAT</span><button class="icon-btn" onclick="closeModal()">×</button></div><div style="text-align:center;padding:12px 0 20px"><span class="eyebrow">Secure email check</span><h2 style="font-size:34px;margin:16px 0 6px">Enter the 4-digit code</h2><p class="muted">Sent to <strong>${esc(VERIFY_EMAIL)}</strong></p><div class="otp-grid">${[0,1,2,3].map(i=>`<input class="otp-box" inputmode="numeric" maxlength="1" oninput="otpMove(this,${i})" onkeydown="otpBack(event,${i})">`).join('')}</div><button class="btn btn-primary" onclick="verifyOtp()">Verify and continue →</button><p class="form-note"><button id="resendBtn" class="small-btn" onclick="resendOtp()">Resend code</button> <span id="otpTimer"></span></p></div>`;openModal();setTimeout(()=>document.querySelector('.otp-box')?.focus(),80);cooldown(30)}
function otpMove(el,i){el.value=el.value.replace(/\D/g,'').slice(-1);if(el.value)document.querySelectorAll('.otp-box')[i+1]?.focus();if([...document.querySelectorAll('.otp-box')].map(x=>x.value).join('').length===4)setTimeout(verifyOtp,100)}function otpBack(e,i){if(e.key==='Backspace'&&!e.target.value)document.querySelectorAll('.otp-box')[i-1]?.focus()}
function cooldown(n){OTP_WAIT=n;const t=setInterval(()=>{OTP_WAIT--;const s=$('#otpTimer'),b=$('#resendBtn');if(s)s.textContent=OTP_WAIT>0?`in ${OTP_WAIT}s`:'';if(b)b.disabled=OTP_WAIT>0;if(OTP_WAIT<=0)clearInterval(t)},1000)}
async function verifyOtp(){const code=[...document.querySelectorAll('.otp-box')].map(x=>x.value).join('');if(code.length!==4)return;try{const path=VERIFY_KIND==='login'?'/auth/email-otp/verify':'/verify-email-4';const d=await api(path,{method:'POST',body:JSON.stringify({email:VERIFY_EMAIL,code})});saveUser(d.user);closeModal();toast('Verified successfully','ok');location.hash=d.user.role==='admin'?'#/admin':'#/profile'}catch(x){document.querySelectorAll('.otp-box').forEach(i=>i.value='');document.querySelector('.otp-box')?.focus();toast(x.message,'error')}}
async function resendOtp(){if(OTP_WAIT>0)return;try{await api(VERIFY_KIND==='login'?'/auth/email-otp/request':'/resend-verification-4',{method:'POST',body:JSON.stringify({email:VERIFY_EMAIL})});cooldown(30);toast('New code sent','ok')}catch(x){toast(x.message,'error')}}
function openModal(){$('#modalBackdrop').classList.add('open');document.body.style.overflow='hidden'}function closeModal(){$('#modalBackdrop').classList.remove('open');document.body.style.overflow=''}function modalBackdrop(e){if(e.target.id==='modalBackdrop')closeModal()}
async function profilePage(params){if(!USER){location.hash='#/login';return''}const tab=params.get('tab')||'overview';let orders=[];try{orders=(await api('/orders')).orders||[]}catch{}return `<div class="page"><div class="shell dashboard"><aside class="side-nav"><button class="${tab==='overview'?'active':''}" onclick="location.hash='#/profile'">Profile</button><button class="${tab==='orders'?'active':''}" onclick="location.hash='#/profile?tab=orders'">Orders</button><button onclick="logout()">Sign out</button></aside><main><div class="panel"><div class="panel-head"><div><span class="eyebrow">Your account</span><h2>${esc(USER.name||'Customer')}</h2></div><span class="product-pill">${USER.emailVerified?'Verified':'Unverified'}</span></div>${tab==='orders'?ordersHtml(orders):profileForm()}</div></main></div></div>`}
function profileForm(){return `<form onsubmit="saveProfile(event)"><div class="form-row"><div class="field"><label>Name</label><input class="input" name="name" value="${esc(USER.name||'')}"></div><div class="field"><label>Phone</label><input class="input" name="phone" value="${esc(USER.phone||'')}"></div></div><div class="field"><label>Email</label><input class="input" value="${esc(USER.email)}" disabled></div><button class="btn btn-primary">Save profile →</button><p class="form-note">Addresses and order history stay attached to this verified account.</p></form>`}
async function saveProfile(e){e.preventDefault();try{const d=await api('/profile',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});saveUser(d.user);toast('Profile updated','ok')}catch(x){toast(x.message,'error')}}
function ordersHtml(rows){if(!rows.length)return'<div class="muted">No orders yet. Your future orders will appear here.</div>';return rows.map(o=>`<div class="panel"><strong>${esc(o.id)}</strong><span class="product-pill">${esc(o.status)}</span><p class="muted">${new Date(o.createdAt).toLocaleDateString('en-IN')} · ${money(o.price)}</p></div>`).join('')}
async function forgotPassword(){const email=prompt('Email address');if(!email)return;try{await api('/forgot-password',{method:'POST',body:JSON.stringify({email})});const code=prompt('Enter the reset code from your email');if(!code)return;const password=prompt('New password (minimum 8 characters)');if(!password)return;await api('/reset-password',{method:'POST',body:JSON.stringify({email,code,password})});toast('Password updated','ok')}catch(x){toast(x.message,'error')}}
