(function rivayatCatalog(root, factory) {
  const products = factory();
  if (typeof module === "object" && module.exports) module.exports = products;
  else root.RIVAYAT_PRODUCTS = products;
})(typeof globalThis !== "undefined" ? globalThis : this, function buildCatalog() {
  const sizes = ["S", "M", "L", "XL", "XXL"];
  const standardStock = { S: 10, M: 14, L: 14, XL: 10, XXL: 6 };
  const product = (entry) => ({
    sizes,
    inventory: { ...standardStock },
    rating: 0,
    reviews: 0,
    badge: "New Arrival",
    active: true,
    gallery: [entry.image],
    sizeChart: {},
    variants: [],
    soldCount: 0,
    details: [
      "Original supplied product photograph",
      "Size and stock can be updated from the admin dashboard",
      "Colour may vary slightly by display"
    ],
    ...entry
  });

  return [
    product({
      id: "india-blue-cricket-fan-jersey",
      slug: "india-blue-cricket-fan-jersey",
      name: "India Blue Cricket Fan Jersey",
      category: "Cricket Jerseys",
      color: "Royal Blue",
      mrp: 1299,
      price: 699,
      badge: "Fan Favourite",
      description: "Blue cricket fan jersey with a lightweight match-day look and comfortable everyday fit.",
      image: "/assets/products/jerseys/india_blue_cricket_jersey.png",
      imageWidth: 736,
      imageHeight: 1308,
      details: ["Breathable sportswear feel", "Regular unisex fit", "Independent fanwear; not represented as official team merchandise"]
    }),
    product({
      id: "india-white-cricket-fan-jersey",
      slug: "india-white-cricket-fan-jersey",
      name: "India White Cricket Fan Jersey",
      category: "Cricket Jerseys",
      color: "White",
      mrp: 1299,
      price: 699,
      description: "White cricket fan jersey with navy detailing for a clean retro-inspired match-day outfit.",
      image: "/assets/products/jerseys/india_white_cricket_jersey.png",
      imageWidth: 736,
      imageHeight: 1308,
      details: ["Lightweight sportswear feel", "Regular unisex fit", "Independent fanwear; not represented as official team merchandise"]
    }),
    product({
      id: "rcb-red-blue-cricket-fan-jersey",
      slug: "rcb-red-blue-cricket-fan-jersey",
      name: "Red & Blue Cricket Fan Jersey",
      category: "Cricket Jerseys",
      color: "Red / Navy",
      mrp: 1399,
      price: 749,
      badge: "Match Day",
      description: "Bold red and navy cricket fan jersey designed for match-day energy and casual street styling.",
      image: "/assets/products/jerseys/rcb_red_blue_jersey.png",
      imageWidth: 736,
      imageHeight: 1308,
      details: ["Athletic crew-neck silhouette", "Regular unisex fit", "Independent fanwear; not represented as official team merchandise"]
    }),
    product({
      id: "ac-red-black-football-fan-jersey",
      slug: "ac-red-black-football-fan-jersey",
      name: "Red & Black Football Fan Jersey",
      category: "Football Jerseys",
      color: "Red / Black",
      mrp: 1399,
      price: 749,
      badge: "Classic Stripes",
      description: "Red-and-black striped football fan jersey with a clean stadium-ready silhouette.",
      image: "/assets/products/jerseys/ac_milan_red_black_jersey.png",
      imageWidth: 736,
      imageHeight: 981,
      details: ["Striped fanwear design", "Comfortable regular fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "ac-white-retro-football-fan-jersey",
      slug: "ac-white-retro-football-fan-jersey",
      name: "White Retro Football Fan Jersey",
      category: "Football Jerseys",
      color: "White / Red",
      mrp: 1399,
      price: 749,
      description: "White retro-style football fan jersey with contrast piping and a relaxed fit.",
      image: "/assets/products/jerseys/ac_milan_white_jersey.png",
      imageWidth: 736,
      imageHeight: 1308,
      details: ["Retro contrast detailing", "Relaxed match-day fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "turin-half-black-white-football-fan-jersey",
      slug: "turin-half-black-white-football-fan-jersey",
      name: "Half Black & White Football Fan Jersey",
      category: "Football Jerseys",
      color: "Black / White",
      mrp: 1399,
      price: 749,
      description: "Split black-and-white football fan jersey with a bold asymmetric finish.",
      image: "/assets/products/jerseys/juventus_half_black_white_jersey.png",
      imageWidth: 900,
      imageHeight: 1200,
      details: ["Half-and-half statement design", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "turin-pink-football-fan-jersey",
      slug: "turin-pink-football-fan-jersey",
      name: "Pink Football Fan Jersey",
      category: "Football Jerseys",
      color: "Pink / Black",
      mrp: 1399,
      price: 749,
      badge: "Trending",
      description: "Pink football fan jersey with black accents for a standout casual or match-day look.",
      image: "/assets/products/jerseys/juventus_pink_jersey.png",
      imageWidth: 736,
      imageHeight: 920,
      details: ["Statement pink colourway", "Comfortable regular fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "turin-brush-stripe-football-fan-jersey",
      slug: "turin-brush-stripe-football-fan-jersey",
      name: "Brush-Stripe Football Fan Jersey",
      category: "Football Jerseys",
      color: "White / Black",
      mrp: 1399,
      price: 749,
      description: "White football fan jersey finished with expressive black brush stripes and gold accents.",
      image: "/assets/products/jerseys/juventus_striped_white_jersey.png",
      imageWidth: 900,
      imageHeight: 1200,
      details: ["Brush-stripe graphic", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "liverpool-red-football-fan-jersey",
      slug: "liverpool-red-football-fan-jersey",
      name: "Red Football Fan Jersey",
      category: "Football Jerseys",
      color: "Red",
      mrp: 1399,
      price: 749,
      badge: "Match Day",
      description: "Rich red football fan jersey with subtle all-over texture for stadium days and streetwear fits.",
      image: "/assets/products/jerseys/liverpool_red_jersey.png",
      imageWidth: 736,
      imageHeight: 920,
      details: ["Tonal textured finish", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "manchester-black-football-fan-jersey",
      slug: "manchester-black-football-fan-jersey",
      name: "Black Football Fan Jersey",
      category: "Football Jerseys",
      color: "Black",
      mrp: 1399,
      price: 749,
      description: "Black football fan jersey with tonal graphics for an understated match-day look.",
      image: "/assets/products/jerseys/manchester_city_black_jersey.png",
      imageWidth: 736,
      imageHeight: 981,
      details: ["Tonal black colourway", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "chicago-23-cream-red-tee",
      slug: "chicago-23-cream-red-tee",
      name: "Chicago 23 Cream & Red Tee",
      category: "T-Shirts",
      color: "Cream / Red",
      mrp: 999,
      price: 549,
      badge: "New Drop",
      description: "Cream V-neck graphic tee with red varsity stripes and an easy oversized feel.",
      image: "/assets/products/tshirts/chicago_23_cream_red_tshirt.png",
      imageWidth: 735,
      imageHeight: 985
    }),
    product({
      id: "chicago-grey-vneck-tee",
      slug: "chicago-grey-vneck-tee",
      name: "Chicago Grey V-Neck Tee",
      category: "T-Shirts",
      color: "Slate Grey",
      mrp: 999,
      price: 549,
      description: "Slate grey V-neck crop tee with a relaxed cut and vintage collegiate script.",
      image: "/assets/products/tshirts/chicago_grey_vneck_tshirt.png",
      imageWidth: 1152,
      imageHeight: 2048
    }),
    product({
      id: "black-graphic-360-shorts",
      slug: "black-graphic-360-shorts",
      name: "Black 360 Graphic Shorts",
      category: "Shorts",
      color: "Black / White",
      mrp: 999,
      price: 499,
      badge: "Street Pick",
      description: "Black drawstring shorts with oversized white side graphics and a relaxed streetwear fit.",
      image: "/assets/products/shorts/black_graphic_shorts.png",
      imageWidth: 1200,
      imageHeight: 1598
    }),
    product({
      id: "powder-blue-graphic-shorts",
      slug: "powder-blue-graphic-shorts",
      name: "Powder Blue Graphic Shorts",
      category: "Shorts",
      color: "Powder Blue / White",
      mrp: 999,
      price: 499,
      description: "Powder blue graphic shorts with an elastic waist and relaxed everyday shape.",
      image: "/assets/products/shorts/blue_graphic_shorts_pair.png",
      imageWidth: 405,
      imageHeight: 539
    }),
    product({
      id: "cherry-blossom-black-shorts",
      slug: "cherry-blossom-black-shorts",
      name: "Cherry Blossom Black Shorts",
      category: "Shorts",
      color: "Black / Red",
      mrp: 1099,
      price: 549,
      badge: "Graphic Drop",
      description: "Black shorts with red cherry-blossom artwork and an easy drawstring waist.",
      image: "/assets/products/shorts/cherry_blossom_black_shorts.png",
      imageWidth: 736,
      imageHeight: 980
    }),
    product({
      id: "new-york-liberty-blue-shorts",
      slug: "new-york-liberty-blue-shorts",
      name: "New York Liberty Blue Shorts",
      category: "Shorts",
      color: "Washed Blue",
      mrp: 1099,
      price: 549,
      description: "Washed blue graphic shorts with a Statue of Liberty print and relaxed summer fit.",
      image: "/assets/products/shorts/new_york_blue_shorts.png",
      imageWidth: 736,
      imageHeight: 980
    }),
    product({
      id: "blue-speckle-square-neck-top",
      slug: "blue-speckle-square-neck-top",
      name: "Blue Speckle Square-Neck Top",
      category: "Women",
      color: "Navy Blue",
      mrp: 1299,
      price: 699,
      badge: "Women’s Edit",
      description: "Navy speckle-print square-neck top with full sleeves and a flattering everyday silhouette.",
      image: "/assets/products/women/blue_spotted_top.png",
      imageWidth: 736,
      imageHeight: 1308
    }),
    product({
      id: "red-printed-kurti-set",
      slug: "red-printed-kurti-set",
      name: "Red Printed Kurti Set",
      category: "Women",
      color: "Red / Ivory",
      mrp: 1699,
      price: 899,
      description: "Red printed kurti paired with ivory bottoms for an easy contemporary ethnic look.",
      image: "/assets/products/women/red_printed_kurti_set.png",
      imageWidth: 736,
      imageHeight: 901
    }),
    product({
      id: "white-floral-embroidered-kurti",
      slug: "white-floral-embroidered-kurti",
      name: "White Floral Embroidered Kurti",
      category: "Women",
      color: "Ivory / Multicolour",
      mrp: 1799,
      price: 999,
      badge: "Rivayat Pick",
      description: "Ivory kurti with colourful floral embroidery and a relaxed, modern length.",
      image: "/assets/products/women/white_floral_kurti.png",
      imageWidth: 736,
      imageHeight: 1308
    }),
    product({
      id: "powder-blue-cropped-hoodie",
      slug: "powder-blue-cropped-hoodie",
      name: "Powder Blue Cropped Hoodie",
      category: "Women",
      color: "Powder Blue",
      mrp: 1499,
      price: 799,
      badge: "Soft Drop",
      description: "Powder blue zip hoodie with a cropped shape, statement lettering, and wide sleeves.",
      image: "/assets/products/collection/clothing_01.png",
      imageWidth: 736,
      imageHeight: 1308
    }),
    product({
      id: "heather-grey-cropped-hoodie",
      slug: "heather-grey-cropped-hoodie",
      name: "Heather Grey Cropped Hoodie",
      category: "Women",
      color: "Heather Grey",
      mrp: 1399,
      price: 749,
      description: "Heather grey cropped hoodie with drawstrings and a soft oversized sleeve line.",
      image: "/assets/products/collection/clothing_02.png",
      imageWidth: 736,
      imageHeight: 980
    }),
    product({
      id: "sage-green-cropped-tee",
      slug: "sage-green-cropped-tee",
      name: "Sage Green Cropped Tee",
      category: "Women",
      color: "Sage Green",
      mrp: 799,
      price: 449,
      description: "Minimal sage green crop tee with a clean crew neck and relaxed short sleeves.",
      image: "/assets/products/collection/clothing_03.png",
      imageWidth: 610,
      imageHeight: 940
    }),
    product({
      id: "caramel-stripe-cropped-polo",
      slug: "caramel-stripe-cropped-polo",
      name: "Caramel Stripe Cropped Polo",
      category: "Women",
      color: "Ivory / Caramel",
      mrp: 999,
      price: 549,
      description: "Striped cropped polo with a caramel collar and neat casual shape.",
      image: "/assets/products/collection/clothing_05.png",
      imageWidth: 750,
      imageHeight: 999
    }),
    product({
      id: "navy-chicago-cropped-polo",
      slug: "navy-chicago-cropped-polo",
      name: "Navy Chicago Cropped Polo",
      category: "Women",
      color: "Navy / White",
      mrp: 999,
      price: 549,
      description: "Navy cropped polo tee with a contrast white collar and collegiate lettering.",
      image: "/assets/products/collection/clothing_06.png",
      imageWidth: 1200,
      imageHeight: 1598
    }),
    product({
      id: "black-plaid-cropped-shacket",
      slug: "black-plaid-cropped-shacket",
      name: "Black Plaid Cropped Shacket",
      category: "Women",
      color: "Black / Brown Plaid",
      mrp: 1899,
      price: 999,
      badge: "Layering Pick",
      description: "Cropped button-up shacket combining solid black panels with warm plaid pockets and sleeves.",
      image: "/assets/products/collection/clothing_07.png",
      imageWidth: 750,
      imageHeight: 999
    }),
    product({
      id: "mustard-plaid-hooded-overshirt",
      slug: "mustard-plaid-hooded-overshirt",
      name: "Mustard Plaid Hooded Overshirt",
      category: "Overshirts",
      color: "Mustard / Blue Plaid",
      mrp: 1999,
      price: 1099,
      description: "Mustard-and-blue plaid overshirt with a grey hood and relaxed layered fit.",
      image: "/assets/products/collection/clothing_08.png",
      imageWidth: 736,
      imageHeight: 981
    }),
    product({
      id: "colourblock-graphic-zip-jacket",
      slug: "colourblock-graphic-zip-jacket",
      name: "Colourblock Graphic Zip Jacket",
      category: "Jackets",
      color: "Grey / Multicolour",
      mrp: 2299,
      price: 1299,
      badge: "Statement Layer",
      description: "Grey zip jacket with a vivid geometric colourblock panel and utility pocket styling.",
      image: "/assets/products/collection/clothing_09.png",
      imageWidth: 750,
      imageHeight: 999
    }),
    product({
      id: "white-89-varsity-tee",
      slug: "white-89-varsity-tee",
      name: "White 89 Varsity Tee",
      category: "T-Shirts",
      color: "White / Charcoal",
      mrp: 999,
      price: 549,
      description: "White oversized V-neck varsity tee with charcoal number graphics and sleeve stars.",
      image: "/assets/products/collection/clothing_11.png",
      imageWidth: 736,
      imageHeight: 1008
    }),
    product({
      id: "barcelona-beige-retro-football-fan-jersey",
      slug: "barcelona-beige-retro-football-fan-jersey",
      name: "Beige Retro Football Fan Jersey",
      category: "Football Jerseys",
      color: "Beige / Navy",
      mrp: 1399,
      price: 749,
      description: "Beige retro-style football fan jersey with navy piping and side stripes.",
      image: "/assets/products/collection/clothing_12.png",
      imageWidth: 735,
      imageHeight: 919,
      details: ["Retro fanwear silhouette", "Relaxed unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "madrid-white-gold-retro-football-fan-jersey",
      slug: "madrid-white-gold-retro-football-fan-jersey",
      name: "White & Gold Retro Football Fan Jersey",
      category: "Football Jerseys",
      color: "White / Gold",
      mrp: 1399,
      price: 749,
      description: "White retro-style football fan jersey with gold and navy wave detailing.",
      image: "/assets/products/collection/clothing_13.png",
      imageWidth: 736,
      imageHeight: 981,
      details: ["Gold contrast detailing", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "madrid-purple-stripe-football-fan-jersey",
      slug: "madrid-purple-stripe-football-fan-jersey",
      name: "Purple Stripe Football Fan Jersey",
      category: "Football Jerseys",
      color: "Ivory / Purple",
      mrp: 1399,
      price: 749,
      badge: "Retro Pick",
      description: "Ivory football fan jersey with a bold central purple stripe and retro collar.",
      image: "/assets/products/collection/clothing_14.png",
      imageWidth: 736,
      imageHeight: 1104,
      details: ["Retro centre-stripe design", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    }),
    product({
      id: "madrid-white-polo-football-fan-jersey",
      slug: "madrid-white-polo-football-fan-jersey",
      name: "White Polo Football Fan Jersey",
      category: "Football Jerseys",
      color: "White / Black",
      mrp: 1399,
      price: 749,
      description: "White polo-collar football fan jersey with black trim for a sharp retro look.",
      image: "/assets/products/collection/clothing_15.png",
      imageWidth: 720,
      imageHeight: 988,
      details: ["Contrast polo collar", "Regular unisex fit", "Independent fanwear; not represented as official club merchandise"]
    })
  ];
});
