let LAUNCH_AVATAR='', LAUNCH_PRODUCT_IMAGES=[];
async function launchCompress(file,max=1400,q=.88){
  if(!file?.type?.startsWith('image/')) throw new Error('Choose an image file.');
  if(file.size>12*1024*1024) throw new Error('Keep the original image under 12 MB.');
  const src=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});
  const im=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=src});
  const scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),c=document.createElement('canvas');
  c.width=Math.round(im.naturalWidth*scale);c.height=Math.round(im.naturalHeight*scale);const x=c.getContext('2d');x.imageSmoothingQuality='high';x.drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/webp',q);
}
function launchAvatar(u,large=''){const initial=esc((u?.name||u?.email||'R').trim().charAt(0).toUpperCase());return u?.avatar?`<img class="profile-avatar ${large}" src="${esc(u.avatar)}" alt="Profile photo" referrerpolicy="no-referrer">`:`<span class="profile-avatar avatar-fallback ${large}">${initial}</span>`}

loginPage=function(params){AUTH_MODE=params.get('mode')||'otp';const visual=findP('emerald-check-overshirt')||PRODUCTS[0];return `<div class="page auth-wrap launch-auth"><div class="shell"><div class="auth-card trust-auth-card"><aside class="auth-visual">${media(visual?.image,'RIVAYAT collection')}<div class="auth-visual-shade"></div><span class="brand">RIVAYAT</span><div><span class="eyebrow">Secure account access</span><h2>Your orders, addresses and favourites in one place.</h2><p>Verified email access. No unnecessary steps.</p></div></aside><section class="auth-panel"><div class="auth-trust-row"><span>Secure account</span><span>4-digit email code</span><span>Google sign-in</span></div><span class="eyebrow">RIVAYAT account</span><h1>${AUTH_MODE==='signup'?'Create your account.':AUTH_MODE==='login'?'Sign in with password.':'Sign in with email.'}</h1><p class="muted">${AUTH_MODE==='otp'?'Enter your email and we will send a secure 4-digit code. No password required.':'Track orders, manage returns and save delivery details.'}</p><div class="auth-tabs"><button class="auth-tab ${AUTH_MODE==='otp'?'active':''}" onclick="authMode('otp')">Email code</button><button class="auth-tab ${AUTH_MODE==='login'?'active':''}" onclick="authMode('login')">Password</button><button class="auth-tab ${AUTH_MODE==='signup'?'active':''}" onclick="authMode('signup')">Create</button></div>${AUTH_MODE==='login'?loginForm():AUTH_MODE==='signup'?signupForm():otpForm()}<div class="auth-divider"><span>or</span></div><div id="googleButton"></div><p class="form-note privacy-note">By continuing, you agree to our <a href="#/terms">Terms</a> and acknowledge our <a href="#/privacy">Privacy Policy</a>.</p></section></div></div></div>`};
otpForm=function(){return `<form onsubmit="requestOtp(event)" class="auth-form"><div class="field"><label>Email</label><input class="input" name="email" type="email" required autocomplete="email" placeholder="you@example.com"></div><button class="btn btn-primary full">Email me a 4-digit code →</button><p class="form-note">The code expires in 10 minutes. No marketing subscription is required.</p></form>`};
showOtp=function(){const m=$('#modal');m.innerHTML=`<div class="modal-head"><span class="brand">RIVAYAT</span><button class="icon-btn" onclick="closeModal()">×</button></div><div class="otp-stage"><div class="otp-mail-icon">✉</div><span class="eyebrow">Secure email check</span><h2>Enter your 4-digit code</h2><p class="muted">Sent to <strong>${esc(VERIFY_EMAIL)}</strong></p><div class="otp-progress"><i></i><i></i><i></i><i></i></div><div class="otp-grid">${[0,1,2,3].map(i=>`<input class="otp-box" inputmode="numeric" autocomplete="one-time-code" maxlength="1" oninput="otpMove(this,${i})" onkeydown="otpBack(event,${i})" onpaste="launchOtpPaste(event)">`).join('')}</div><div id="otpStatus" class="otp-status">0/4 digits entered</div><button id="verifyOtpBtn" class="btn btn-primary full" onclick="verifyOtp()">Verify and continue →</button><p class="form-note"><button id="resendBtn" class="small-btn" onclick="resendOtp()">Resend code</button> <span id="otpTimer"></span></p></div>`;openModal();setTimeout(()=>document.querySelector('.otp-box')?.focus(),100);cooldown(30)};
function launchOtpPaint(){const b=[...document.querySelectorAll('.otp-box')],d=[...document.querySelectorAll('.otp-progress i')];b.forEach((x,i)=>{x.classList.toggle('filled',!!x.value);d[i]?.classList.toggle('filled',!!x.value)});const n=b.filter(x=>x.value).length;if($('#otpStatus'))$('#otpStatus').textContent=n===4?'Code complete — verifying…':`${n}/4 digits entered`}
otpMove=function(el,i){el.value=el.value.replace(/\D/g,'').slice(-1);launchOtpPaint();if(el.value)document.querySelectorAll('.otp-box')[i+1]?.focus();if([...document.querySelectorAll('.otp-box')].map(x=>x.value).join('').length===4)setTimeout(verifyOtp,180)};
function launchOtpPaste(e){const code=(e.clipboardData?.getData('text')||'').replace(/\D/g,'').slice(0,4);if(code.length!==4)return;e.preventDefault();document.querySelectorAll('.otp-box').forEach((x,i)=>x.value=code[i]||'');launchOtpPaint();setTimeout(verifyOtp,180)}

profilePage=async function(params){if(!USER){location.hash='#/login?mode=otp';return''}const tab=params.get('tab')||'overview';let orders=[];try{orders=(await api('/orders')).orders||[]}catch{}const tabs=[['overview','Overview'],['addresses','Addresses'],['orders','Orders'],['security','Security & privacy']];return `<div class="page profile-page"><div class="shell profile-shell"><aside class="profile-sidebar"><div class="profile-person">${launchAvatar(USER)}<div><strong>${esc(USER.name||'Customer')}</strong><span>${esc(USER.email||'')}</span></div></div><nav>${tabs.map(([k,n])=>`<button class="${tab===k?'active':''}" onclick="location.hash='#/profile${k==='overview'?'':'?tab='+k}'">${n}</button>`).join('')}</nav><button class="profile-signout" onclick="logout()">Sign out</button></aside><main class="profile-main">${launchProfileContent(tab,orders)}</main></div></div>`};
function launchProfileContent(tab,orders){if(tab==='orders')return launchOrders(orders);if(tab==='addresses')return launchAddresses();if(tab==='security')return launchSecurity();return launchOverview(orders)}
function launchOverview(orders){return `<section class="profile-hero-card"><div>${launchAvatar(USER,'large')}<div><span class="eyebrow">${USER.emailVerified?'Verified account':'Account'}</span><h1>${esc(USER.name||'Customer')}</h1><p>${esc(USER.email)}</p></div></div><span class="verified-chip">${USER.emailVerified?'✓ Email verified':'Verification pending'}</span></section><div class="profile-stat-grid"><div><strong>${orders.length}</strong><span>Orders</span></div><div><strong>${(USER.addresses||[]).length}</strong><span>Addresses</span></div><div><strong>${USER.authProvider==='google'?'Google':USER.authProvider==='hybrid'?'Google + email':'Email'}</strong><span>Sign-in</span></div></div><section class="panel profile-edit-card"><div class="panel-head"><div><span class="eyebrow">Personal details</span><h2>Make checkout faster</h2></div></div><div class="avatar-editor"><div id="launchAvatarPreview">${launchAvatar(USER,'large')}</div><div><label class="btn btn-secondary">Change photo<input hidden type="file" accept="image/*" onchange="launchProfilePhoto(event)"></label><p class="form-note">Google sign-in automatically uses your Google profile picture. You can replace it here.</p></div></div><form onsubmit="launchSaveProfile(event)"><div class="form-row"><div class="field"><label>Name</label><input class="input" name="name" required value="${esc(USER.name||'')}"></div><div class="field"><label>Phone</label><input class="input" name="phone" value="${esc(USER.phone||'')}"></div></div><div class="field"><label>Email</label><input class="input" disabled value="${esc(USER.email||'')}"></div><button class="btn btn-primary">Save changes →</button></form></section>`}
async function launchProfilePhoto(e){try{LAUNCH_AVATAR=await launchCompress(e.target.files?.[0],600,.86);$('#launchAvatarPreview').innerHTML=`<img class="profile-avatar large" src="${LAUNCH_AVATAR}" alt="Profile preview">`;toast('Photo ready — save changes','ok')}catch(x){toast(x.message,'error')}}
async function launchSaveProfile(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(LAUNCH_AVATAR)f.avatar=LAUNCH_AVATAR;try{const d=await api('/launch/profile',{method:'PUT',body:JSON.stringify(f)});saveUser(d.user);LAUNCH_AVATAR='';toast('Profile updated','ok');render()}catch(x){toast(x.message,'error')}}
function launchAddresses(){const a=USER.addresses||[];return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">Delivery</span><h2>Saved addresses</h2></div><button class="btn btn-primary" onclick="launchAddressEditor()">Add address</button></div>${a.length?`<div class="address-grid">${a.map((x,i)=>`<article class="address-card"><strong>${esc(x.label||'Address')}</strong><p>${esc(x.line1||'')}<br>${esc(x.city||'')}, ${esc(x.state||'')} ${esc(x.pincode||'')}</p><button class="small-btn" onclick="launchAddressEditor(${i})">Edit</button> <button class="small-btn danger" onclick="launchRemoveAddress(${i})">Remove</button></article>`).join('')}</div>`:'<p class="muted">No saved addresses yet.</p>'}</section>`}
function launchAddressEditor(i=-1){const x=(USER.addresses||[])[i]||{};$('#modal').innerHTML=`<div class="modal-head"><h2>${i<0?'Add':'Edit'} address</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form onsubmit="launchSaveAddress(event,${i})"><div class="field"><label>Label</label><input class="input" name="label" value="${esc(x.label||'Home')}"></div><div class="field"><label>Address</label><input class="input" name="line1" required value="${esc(x.line1||'')}"></div><div class="form-row"><div class="field"><label>City</label><input class="input" name="city" required value="${esc(x.city||'')}"></div><div class="field"><label>State</label><input class="input" name="state" required value="${esc(x.state||'')}"></div></div><div class="field"><label>Pincode</label><input class="input" name="pincode" required pattern="[0-9]{6}" maxlength="6" value="${esc(x.pincode||'')}"></div><button class="btn btn-primary full">Save address →</button></form>`;openModal()}
async function launchSaveAddress(e,i){e.preventDefault();const rows=[...(USER.addresses||[])],x=Object.fromEntries(new FormData(e.currentTarget));i<0?rows.push(x):rows[i]=x;const d=await api('/launch/profile',{method:'PUT',body:JSON.stringify({addresses:rows})});saveUser(d.user);closeModal();toast('Address saved','ok');render()}
async function launchRemoveAddress(i){if(!confirm('Remove this address?'))return;const rows=(USER.addresses||[]).filter((_,n)=>n!==i),d=await api('/launch/profile',{method:'PUT',body:JSON.stringify({addresses:rows})});saveUser(d.user);render()}
function launchOrders(rows){return `<section><div class="profile-section-head"><div><span class="eyebrow">Order history</span><h1>Your orders</h1></div><span class="muted">Status changes are emailed automatically.</span></div>${rows.length?`<div class="order-card-list">${rows.map(o=>`<article class="order-card-pro"><div class="order-card-head"><div><span>${new Date(o.createdAt).toLocaleDateString('en-IN')}</span><strong>${esc(o.id)}</strong></div><span class="order-status">${esc(o.status)}</span></div><div class="order-card-foot"><span>${(o.items||[]).length||1} item(s)</span><strong>${money(o.price)}</strong></div></article>`).join('')}</div>`:'<div class="panel"><h2>No orders yet.</h2><a class="btn btn-primary" href="#/shop">Shop now →</a></div>'}</section>`}
function launchSecurity(){return `<section class="panel"><span class="eyebrow">Security & privacy</span><h2>Account controls</h2><div class="security-list"><div><strong>Passwordless sign-in</strong><span>Use a fresh 4-digit email code whenever you sign in.</span><button class="small-btn" onclick="location.hash='#/login?mode=otp'">Use email code</button></div><div><strong>Privacy</strong><span>Review collection, retention and your privacy rights.</span><button class="small-btn" onclick="location.hash='#/privacy'">Privacy policy</button></div><div class="danger-zone"><strong>Delete account</strong><span>Permanently remove your login profile and saved account data. Transaction records can be retained where required.</span><button class="btn btn-danger" onclick="launchDeleteDialog()">Delete my account</button></div></div></section>`}
function launchDeleteDialog(){$('#modal').innerHTML=`<div class="modal-head"><h2>Delete account</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p>This cannot be undone. Type <strong>DELETE</strong> to continue.</p><input id="launchDeleteConfirm" class="input" placeholder="DELETE"><button class="btn btn-danger full" onclick="launchDeleteAccount()">Permanently delete account</button>`;openModal()}
async function launchDeleteAccount(){if($('#launchDeleteConfirm')?.value!=='DELETE')return toast('Type DELETE to confirm','error');try{await api('/launch/account',{method:'DELETE',body:JSON.stringify({confirmation:'DELETE'})});USER=null;localStorage.removeItem('rivayat_user');closeModal();toast('Account deleted','ok');location.hash='#/'}catch(x){toast(x.message,'error')}}

adminPage=async function(params){if(!USER||USER.role!=='admin'){location.hash='#/login';return''}ADMIN_TAB=params.get('tab')||ADMIN_TAB;let d={};try{if(ADMIN_TAB==='overview')d.stats=(await api('/admin/stats')).stats||{};if(ADMIN_TAB==='products')d.products=(await api('/products')).products||[];if(ADMIN_TAB==='orders')d.orders=(await api('/orders')).orders||[];if(ADMIN_TAB==='customers')d.users=(await api('/users')).users||[];if(ADMIN_TAB==='returns')d.returns=(await api('/returns')).requests||[];if(ADMIN_TAB==='coupons')d.coupons=(await api('/coupons')).coupons||[];if(ADMIN_TAB==='homepage')d.home=HOME;if(ADMIN_TAB==='legal')d.legal=(await api('/launch/legal-settings')).settings||{}}catch(e){toast(e.message,'error')}return `<div class="page"><div class="shell dashboard"><aside class="side-nav">${[['overview','Overview'],['products','Products'],['orders','Orders'],['customers','Customers'],['returns','Returns'],['coupons','Coupons'],['homepage','Homepage'],['legal','Legal & trust']].map(([k,n])=>`<button class="${ADMIN_TAB===k?'active':''}" onclick="location.hash='#/admin?tab=${k}'">${n}</button>`).join('')}<button onclick="location.hash='#/'">View store ↗</button><button onclick="logout()">Sign out</button></aside><main>${launchAdminContent(d)}</main></div></div>`}
function launchAdminContent(d){if(ADMIN_TAB==='products')return launchAdminProducts(d.products||[]);if(ADMIN_TAB==='orders')return adminOrders(d.orders||[]);if(ADMIN_TAB==='legal')return launchLegalAdmin(d.legal||{});return adminContent(d)}
function launchAdminProducts(rows){return `<div class="panel"><div class="panel-head"><div><span class="eyebrow">Catalogue control</span><h2>Products</h2></div><button class="btn btn-primary" onclick="launchProductEditor()">Add product</button></div><p class="admin-note">Every live product can be edited here: copy, price, stock, sizes and images. Drop images directly into the editor.</p><div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th></th></tr></thead><tbody>${rows.filter(p=>p.active!==false).map(p=>`<tr><td><div class="admin-product-cell">${media(p.image,p.name,'mini-img')}<div><strong>${esc(p.name)}</strong><span>${esc(p.color||'')}</span></div></div></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${Object.values(p.inventory||{}).reduce((s,n)=>s+Number(n||0),0)}</td><td><button class="small-btn" onclick="launchProductEditor('${esc(p.id)}')">Edit</button></td></tr>`).join('')}</tbody></table></div></div>`}
function launchProductEditor(id=''){const p=(id&&findP(id))||{sizes:['S','M','L','XL'],inventory:{S:10,M:10,L:10,XL:10},category:'Shirts'};LAUNCH_PRODUCT_IMAGES=[p.image,...(p.gallery||[])].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);$('#modal').innerHTML=`<div class="modal-head"><h2>${id?'Edit product':'Add product'}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form onsubmit="launchSaveProduct(event,'${esc(id)}')"><div class="admin-media-editor"><div id="launchDropzone" class="media-dropzone" ondragover="launchDrag(event,true)" ondragleave="launchDrag(event,false)" ondrop="launchDrop(event)"><strong>Drag & drop product photos</strong><span>or click to browse · JPG, PNG, WebP · up to 8 images</span><input type="file" accept="image/*" multiple onchange="launchPickImages(event)"></div><div id="launchMediaPreview" class="gallery-preview">${launchMediaPreview()}</div></div><div class="form-row"><div class="field"><label>Name</label><input class="input" name="name" required value="${esc(p.name||'')}"></div><div class="field"><label>Category</label><select class="select" name="category">${['Hoodies','Cargos','Jackets','Shirts'].map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="form-row"><div class="field"><label>Price</label><input class="input" type="number" name="price" required value="${p.price||''}"></div><div class="field"><label>MRP</label><input class="input" type="number" name="mrp" value="${p.mrp||''}"></div></div><div class="form-row"><div class="field"><label>Color</label><input class="input" name="color" value="${esc(p.color||'')}"></div><div class="field"><label>Badge</label><input class="input" name="badge" value="${esc(p.badge||'NEW')}"></div></div><div class="field"><label>Description</label><textarea class="textarea" name="description">${esc(p.description||'')}</textarea></div><div class="field"><label>Sizes</label><input class="input" name="sizes" value="${esc((p.sizes||[]).join(','))}"></div><div class="field"><label>Stock per size</label><input class="input" name="stocks" value="${esc((p.sizes||[]).map(s=>p.inventory?.[s]??10).join(','))}"></div><button class="btn btn-primary full">Save product →</button></form>`;openModal()}
function launchMediaPreview(){return LAUNCH_PRODUCT_IMAGES.map((x,i)=>`<div>${media(x,'Product image')}<span>${i===0?'Primary':'Gallery'}</span><button type="button" onclick="launchRemoveMedia(${i})">×</button></div>`).join('')}
function launchDrag(e,on){e.preventDefault();$('#launchDropzone')?.classList.toggle('dragging',on)}
async function launchDrop(e){e.preventDefault();launchDrag(e,false);await launchAddFiles([...e.dataTransfer.files])}
async function launchPickImages(e){await launchAddFiles([...e.target.files])}
async function launchAddFiles(files){try{for(const f of files.slice(0,8-LAUNCH_PRODUCT_IMAGES.length))LAUNCH_PRODUCT_IMAGES.push(await launchCompress(f,1600,.88));$('#launchMediaPreview').innerHTML=launchMediaPreview()}catch(x){toast(x.message,'error')}}
function launchRemoveMedia(i){LAUNCH_PRODUCT_IMAGES.splice(i,1);$('#launchMediaPreview').innerHTML=launchMediaPreview()}
async function launchSaveProduct(e,id){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),sizes=String(f.sizes||'').split(',').map(x=>x.trim()).filter(Boolean),stocks=String(f.stocks||'').split(',').map(Number),inventory={};sizes.forEach((s,i)=>inventory[s]=Number.isFinite(stocks[i])?stocks[i]:10);const body={id:id||`product-${Date.now()}`,slug:id||String(f.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name:f.name,category:f.category,price:Number(f.price),mrp:Number(f.mrp||f.price),color:f.color,badge:f.badge,description:f.description,sizes,inventory,image:LAUNCH_PRODUCT_IMAGES[0]||'',gallery:LAUNCH_PRODUCT_IMAGES,active:true,tier:findP(id)?.tier||'standard'};try{await api('/launch/products',{method:'POST',body:JSON.stringify(body)});closeModal();toast('Product saved','ok');await loadData();render()}catch(x){toast(x.message,'error')}}
changeOrderStatus=async function(id,status){try{const d=await api('/launch/orders/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})});toast(d.email?.success?'Order updated and customer emailed':'Order updated','ok')}catch(x){toast(x.message,'error')}}
changeReturn=async function(id,status){try{await api('/launch/returns/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})});toast('Return updated and customer notified','ok')}catch(x){toast(x.message,'error')}}
function launchLegalAdmin(s){const missing=!s.businessAddress||!s.grievanceOfficer;return `<div class="panel"><div class="panel-head"><div><span class="eyebrow">Launch compliance</span><h2>Legal & customer trust</h2></div><span class="product-pill ${missing?'warning':''}">${missing?'Action required':'Configured'}</span></div>${missing?'<div class="launch-warning"><strong>Complete your real business details before public launch.</strong><span>Do not publish placeholder identity or grievance information.</span></div>':''}<form onsubmit="launchSaveLegal(event)"><div class="field"><label>Legal/operator name</label><input class="input" name="operator" required value="${esc(s.operator||'RIVAYAT')}"></div><div class="field"><label>Business/postal address</label><textarea class="textarea" name="businessAddress" required>${esc(s.businessAddress||'')}</textarea></div><div class="form-row"><div class="field"><label>Privacy/support email</label><input class="input" type="email" name="privacyEmail" required value="${esc(s.privacyEmail||'support@rivayat.in')}"></div><div class="field"><label>Support phone</label><input class="input" name="supportPhone" value="${esc(s.supportPhone||'')}"></div></div><div class="form-row"><div class="field"><label>Grievance contact name</label><input class="input" name="grievanceOfficer" required value="${esc(s.grievanceOfficer||'')}"></div><div class="field"><label>Grievance email</label><input class="input" type="email" name="grievanceEmail" required value="${esc(s.grievanceEmail||s.privacyEmail||'support@rivayat.in')}"></div></div><div class="field"><label>GSTIN (if applicable)</label><input class="input" name="gstin" value="${esc(s.gstin||'')}"></div><div class="field"><label>Return window (days)</label><input class="input" type="number" min="1" max="30" name="returnDays" value="${Number(s.returnDays||7)}"></div><button class="btn btn-primary">Save legal settings →</button><p class="form-note">The policy framework is compliance-oriented, but business-specific legal/tax terms should be reviewed by a qualified professional before launch.</p></form></div>`}
async function launchSaveLegal(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.returnDays=Number(body.returnDays||7);try{const d=await api('/launch/legal-settings',{method:'PUT',body:JSON.stringify(body)});Object.assign(LEGAL,d.settings||{});LEGAL.email=LEGAL.privacyEmail||LEGAL.email;toast('Legal settings saved','ok');render()}catch(x){toast(x.message,'error')}}
const __launchNotFound=notFound;
notFound=function(){const p=(location.hash||'#/').replace(/^#/,'').split('?')[0];if(['/privacy','/terms','/returns-policy','/shipping','/cookies'].includes(p))return legalPage(p.slice(1));return __launchNotFound()};
window.addEventListener('load',async()=>{try{await loadLegalSettings()}catch{};ensurePrivacyBanner()});
