const fs=require('fs');const path=require('path');const crypto=require('crypto');const bcrypt=require('bcryptjs');const mongoose=require('mongoose');
const {app,startServer,createToken}=require('./server');
const APP_SECRET=process.env.APP_SECRET||'';const RESEND_API_KEY=process.env.RESEND_API_KEY||'';const EMAIL_FROM=process.env.EMAIL_FROM||'RIVAYAT <orders@rivayat.in>';
const User=mongoose.model('User'),Product=mongoose.model('Product'),EmailVerification=mongoose.model('EmailVerification');
const norm=e=>String(e||'').trim().toLowerCase();const same=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)};
const hash=(email,code,kind='verify')=>crypto.createHmac('sha256',APP_SECRET).update(`${kind}:${norm(email)}:${String(code).trim()}`).digest('hex');
async function sendEmail(to,subject,html){if(!RESEND_API_KEY)return{success:false};try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${RESEND_API_KEY}`},body:JSON.stringify({from:EMAIL_FROM,to:[to],subject,html})});return{success:r.ok}}catch{return{success:false}}}
async function issue(user,kind='verify',throttle=false){const email=norm(user.email);if(throttle){const recent=await EmailVerification.findOne({email,usedAt:null,createdAt:{$gt:new Date(Date.now()-30000)}});if(recent){const e=new Error('Please wait 30 seconds before requesting another code.');e.statusCode=429;throw e}}
const code=String(crypto.randomInt(1000,10000));await EmailVerification.updateMany({email,usedAt:null},{$set:{usedAt:new Date()}});await EmailVerification.create({email,codeHash:hash(email,code,kind),expiresAt:new Date(Date.now()+10*60*1000)});const result=await sendEmail(email,kind==='login'?'Your RIVAYAT sign-in code':'Verify your RIVAYAT email',`<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;color:#111"><h1 style="letter-spacing:5px">RIVAYAT</h1><p>${kind==='login'?'Use this code to sign in:':'Use this code to verify your email:'}</p><div style="font-size:42px;font-weight:900;letter-spacing:14px;margin:28px 0">${code}</div><p>This code expires in 10 minutes.</p></div>`);return{delivered:result.success,code:process.env.NODE_ENV!=='production'?code:undefined}}
async function consume(email,code,kind){const row=await EmailVerification.findOne({email:norm(email),usedAt:null,expiresAt:{$gt:new Date()}}).sort({createdAt:-1});if(!row||!same(row.codeHash,hash(email,code,kind)))return null;row.usedAt=new Date();await row.save();return row}
app.post('/signup-v2',async(req,res)=>{try{const{name,email,phone,password}=req.body||{};if(!name||!email||!password)return res.status(400).json({success:false,message:'Name, email and password are required.'});if(String(password).length<8)return res.status(400).json({success:false,message:'Password must be at least 8 characters.'});const clean=norm(email);let user=await User.findOne({email:clean});if(user?.emailVerified)return res.status(409).json({success:false,message:'Email already registered. Please sign in.'});if(!user)user=new User({name:String(name).trim(),email:clean,phone:String(phone||'').trim(),role:'customer',emailVerified:false,authProvider:'password'});user.name=String(name).trim();user.phone=String(phone||'').trim();user.password=await bcrypt.hash(String(password),12);await user.save();const v=await issue(user,'verify');if(!v.delivered&&process.env.NODE_ENV==='production')return res.status(503).json({success:false,message:'Email delivery is not configured. Add RESEND_API_KEY and EMAIL_FROM.'});res.json({success:true,email:clean,requiresVerification:true,message:'We sent a 4-digit code to your email.',verificationCode:v.code})}catch(e){res.status(e.statusCode||500).json({success:false,message:e.message})}});
app.post('/verify-email-4',async(req,res)=>{try{const email=norm(req.body.email),code=String(req.body.code||'');if(!(await consume(email,code,'verify')))return res.status(400).json({success:false,message:'Invalid or expired code.'});const user=await User.findOne({email});if(!user)return res.status(404).json({success:false,message:'Account not found.'});user.emailVerified=true;user.lastLoginAt=new Date();await user.save();res.json({success:true,user:{id:user._id,name:user.name,email:user.email,phone:user.phone,role:user.role,addresses:user.addresses||[],emailVerified:true,authProvider:user.authProvider,avatar:user.avatar||'',token:createToken(user)}})}catch(e){res.status(500).json({success:false,message:e.message})}});
app.post('/resend-verification-4',async(req,res)=>{try{const user=await User.findOne({email:norm(req.body.email)});if(!user)return res.json({success:true});if(user.emailVerified)return res.json({success:true,verified:true});const v=await issue(user,'verify',true);res.json({success:true,verificationCode:v.code})}catch(e){res.status(e.statusCode||500).json({success:false,message:e.message})}});
app.post('/login-v2',async(req,res)=>{try{const id=String(req.body.identifier||req.body.email||'').trim(),password=String(req.body.password||'');const user=await User.findOne({$or:[{email:norm(id)},{username:id}]});if(!user||!user.password||!(await bcrypt.compare(password,user.password)))return res.status(401).json({success:false,message:'Incorrect email/username or password.'});if(!user.emailVerified)return res.status(403).json({success:false,requiresVerification:true,email:user.email,message:'Verify your email to continue.'});user.lastLoginAt=new Date();await user.save();res.json({success:true,user:{id:user._id,name:user.name,email:user.email,phone:user.phone,role:user.role,addresses:user.addresses||[],emailVerified:true,authProvider:user.authProvider,avatar:user.avatar||'',token:createToken(user)}})}catch(e){res.status(500).json({success:false,message:e.message})}});
app.post('/auth/email-otp/request',async(req,res)=>{try{const user=await User.findOne({email:norm(req.body.email),emailVerified:true});if(user)await issue(user,'login',true);res.json({success:true,message:'If the account exists, a code has been sent.'})}catch(e){res.status(e.statusCode||500).json({success:false,message:e.message})}});
app.post('/auth/email-otp/verify',async(req,res)=>{try{const email=norm(req.body.email),code=String(req.body.code||'');const user=await User.findOne({email,emailVerified:true});if(!user||!(await consume(email,code,'login')))return res.status(400).json({success:false,message:'Invalid or expired code.'});user.lastLoginAt=new Date();await user.save();res.json({success:true,user:{id:user._id,name:user.name,email:user.email,phone:user.phone,role:user.role,addresses:user.addresses||[],emailVerified:true,authProvider:user.authProvider,avatar:user.avatar||'',token:createToken(user)}})}catch(e){res.status(500).json({success:false,message:e.message})}});
const OLD=['static-noise-oversized-tee','after-hours-oversized-tee','signal-boxy-tee-acid-grey','studio-cargo-01-graphite','utility-cargo-02-olive','wide-leg-denim-01','night-shift-denim-02','sunday-heavyweight-hoodie','zero-hour-hoodie-black','mono-coord-set-stone','archive-zip-shirt-ecru','noir-sculpt-overshirt','noir-tailored-cargo','noir-varsity-jacket','noir-structured-trouser','rivayat-half-pant-black','rivayat-half-pant-white','rivayat-full-pant'];
async function seed(){let items=[];try{items=JSON.parse(fs.readFileSync(path.join(__dirname,'catalog-2026.json'),'utf8'))}catch{};await Product.updateMany({id:{$in:OLD}},{$set:{active:false,updatedAt:new Date()}});for(const p of items)await Product.findOneAndUpdate({id:p.id},{$set:{...p,active:true,updatedAt:new Date()}},{upsert:true,setDefaultsOnInsert:true})}
function buildSprite(){try{const dir=path.join(__dirname,'asset_chunks');const data=fs.readdirSync(dir).sort().map(n=>fs.readFileSync(path.join(dir,n),'utf8')).join('');fs.mkdirSync(path.join(__dirname,'assets'),{recursive:true});fs.writeFileSync(path.join(__dirname,'assets','catalog-2026.webp'),Buffer.from(data,'base64'))}catch(e){console.warn('Product sprite unavailable:',e.message)}}
buildSprite();startServer().then(async()=>{await seed();console.log('RIVAYAT 2026 storefront ready')}).catch(e=>{console.error(e);process.exit(1)});
