const crypto = require('crypto');
const mongoose = require('mongoose');
const { app, authContext, deliveryChargeByPincode } = require('./server');

const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID || '';
const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET || '';
const RESEND_API_KEY = process.env.RESEND_API_KEY || '';
const EMAIL_FROM = process.env.EMAIL_FROM || 'RIVAYAT <orders@rivayat.in>';

const Product = mongoose.model('Product');
const Order = mongoose.model('Order');
const User = mongoose.model('User');
const SiteSetting = mongoose.model('SiteSetting');

const PaymentSessionSchema = new mongoose.Schema({
  internalId: { type: String, required: true, unique: true, index: true },
  razorpayOrderId: { type: String, unique: true, sparse: true },
  amountPaise: Number, subtotal: Number, delivery: Number, total: Number,
  customer: Object, address: Object, items: Array,
  status: { type: String, default: 'Created' }, paymentId: { type: String, default: '' }, signature: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now }, updatedAt: { type: Date, default: Date.now }
});
const ProductReviewSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true, index: true }, productId: { type: String, required: true, index: true },
  reviewerEmail: { type: String, required: true, lowercase: true, index: true }, reviewerName: { type: String, required: true },
  rating: { type: Number, min: 1, max: 5, required: true }, title: { type: String, default: '' }, text: { type: String, required: true },
  verifiedPurchase: { type: Boolean, default: false }, status: { type: String, enum: ['Pending','Approved','Rejected'], default: 'Pending' },
  createdAt: { type: Date, default: Date.now }, updatedAt: { type: Date, default: Date.now }
});
ProductReviewSchema.index({ productId: 1, reviewerEmail: 1 }, { unique: true });
const PaymentSession = mongoose.models.RivayatPaymentSession || mongoose.model('RivayatPaymentSession', PaymentSessionSchema);
const ProductReview = mongoose.models.RivayatProductReview || mongoose.model('RivayatProductReview', ProductReviewSchema);
const ORDER_STATUSES = ['Pending','Confirmed','Packed','Shipped','Out for Delivery','Delivered','Cancelled'];
const normalizeEmail = value => String(value || '').trim().toLowerCase();
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function adminOnly(req,res){const auth=authContext(req);if(auth.role==='admin')return auth;res.status(403).json({success:false,message:'Admin access required.'});return null}
async function sendEmail(to,subject,html){if(!RESEND_API_KEY||!to)return{skipped:true,reason:'Email is not configured.'};try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${RESEND_API_KEY}`},body:JSON.stringify({from:EMAIL_FROM,to:[to],subject,html})});if(!r.ok)throw new Error(`Email provider returned ${r.status}`);return{success:true}}catch(error){return{success:false,message:error.message}}}
function safeEqualText(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function orderEmail(order,headline,intro){const items=(order.items||[]).map(i=>`<tr><td style="padding:9px 0">${escapeHtml(i.name||'')}<br><span style="color:#777">${escapeHtml(i.size||'')} × ${Number(i.qty||1)}</span></td><td style="padding:9px 0;text-align:right">₹${Number(i.price||0).toLocaleString('en-IN')}</td></tr>`).join('');return `<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#111;padding:28px"><div style="letter-spacing:5px;font-weight:900;font-size:22px">RIVAYAT</div><p style="color:#777">Order ${escapeHtml(order.id)}</p><h1 style="font-size:30px">${escapeHtml(headline)}</h1><p style="line-height:1.6;color:#555">${escapeHtml(intro)}</p><table style="width:100%;border-collapse:collapse;margin:24px 0">${items}</table><div style="border-top:1px solid #ddd;padding-top:14px"><strong>Total: ₹${Number(order.price||0).toLocaleString('en-IN')}</strong></div><p style="margin-top:28px;color:#777;font-size:13px">This is a transactional email about your RIVAYAT order.</p></div>`}
async function priceCart(items=[],pincode=''){if(!Array.isArray(items)||!items.length)throw Object.assign(new Error('Your bag is empty.'),{statusCode:400});const cleaned=items.slice(0,30).map(x=>({id:String(x.id||x.productId||''),size:String(x.size||''),qty:Math.max(1,Math.min(10,Number(x.qty||1)))}));if(cleaned.some(x=>!x.id))throw Object.assign(new Error('A product is missing from the order.'),{statusCode:400});const products=await Product.find({id:{$in:[...new Set(cleaned.map(x=>x.id))]},active:{$ne:false}}),map=new Map(products.map(p=>[p.id,p])),orderItems=[];for(const line of cleaned){const p=map.get(line.id);if(!p)throw Object.assign(new Error('One of the products is no longer available.'),{statusCode:409});if(p.sizes?.length&&line.size&&!p.sizes.includes(line.size))throw Object.assign(new Error(`${p.name}: invalid size.`),{statusCode:400});const stock=Number(p.inventory?.[line.size]??999);if(line.qty>stock)throw Object.assign(new Error(`${p.name}: only ${stock} left in ${line.size}.`),{statusCode:409});orderItems.push({id:p.id,productId:p.id,name:p.name,size:line.size,qty:line.qty,price:Number(p.price||0),image:p.image||''})}const subtotal=orderItems.reduce((s,x)=>s+x.price*x.qty,0),delivery=Number(deliveryChargeByPincode(pincode,subtotal));return{items:orderItems,subtotal,delivery,total:subtotal+delivery}}
function validateCustomer(input={}){const customerName=String(input.customerName||input.name||'').trim().slice(0,120),phone=String(input.phone||'').trim().slice(0,30),email=normalizeEmail(input.email),address=input.address||{};if(!customerName||!phone||!email)throw Object.assign(new Error('Name, phone and email are required.'),{statusCode:400});if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(new Error('Enter a valid email address.'),{statusCode:400});if(!String(address.line1||'').trim()||!String(address.city||'').trim()||!String(address.state||'').trim()||!/^\d{6}$/.test(String(address.pincode||'')))throw Object.assign(new Error('Enter a complete delivery address and 6-digit pincode.'),{statusCode:400});return{customerName,phone,email,address:{line1:String(address.line1).trim(),city:String(address.city).trim(),state:String(address.state).trim(),pincode:String(address.pincode).trim()}}}
async function razorpayRequest(path,body){if(!RAZORPAY_KEY_ID||!RAZORPAY_KEY_SECRET)throw Object.assign(new Error('Razorpay is not configured on the server.'),{statusCode:503});const auth=Buffer.from(`${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}`).toString('base64'),r=await fetch(`https://api.razorpay.com/v1${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Basic ${auth}`},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data?.error?.description||`Razorpay returned ${r.status}`),{statusCode:502});return data}
app.get('/launch/diagnostics',async(req,res)=>{try{await mongoose.connection.db.admin().ping();res.json({success:true,backend:'connected',database:'connected',emailConfigured:Boolean(RESEND_API_KEY),razorpayConfigured:Boolean(RAZORPAY_KEY_ID&&RAZORPAY_KEY_SECRET),apiVersion:'2026.08.18'})}catch(error){res.status(503).json({success:false,message:error.message})}});
app.get('/launch/payment/config',(req,res)=>res.json({success:true,keyId:RAZORPAY_KEY_ID||'',configured:Boolean(RAZORPAY_KEY_ID&&RAZORPAY_KEY_SECRET)}));
app.post('/launch/orders/cod',async(req,res)=>{try{const customer=validateCustomer(req.body||{}),priced=await priceCart(req.body.items,customer.address.pincode),id=`RIV${Date.now().toString().slice(-9)}${crypto.randomInt(10,99)}`,order=await Order.create({id,...customer,subtotal:priced.subtotal,discount:0,delivery:priced.delivery,price:priced.total,paymentMethod:'COD',paymentStatus:'Pending',status:'Pending',address:customer.address,items:priced.items}),email=await sendEmail(order.email,`RIVAYAT order confirmed: ${order.id}`,orderEmail(order,'Order confirmed.','We have received your order and will email you when its status changes.'));res.json({success:true,order,email})}catch(error){res.status(error.statusCode||500).json({success:false,message:error.message})}});
app.post('/launch/payment/order',async(req,res)=>{try{const customer=validateCustomer(req.body||{}),priced=await priceCart(req.body.items,customer.address.pincode),internalId=`RIV${Date.now().toString().slice(-9)}${crypto.randomInt(100,999)}`,rp=await razorpayRequest('/orders',{amount:Math.round(priced.total*100),currency:'INR',receipt:internalId,notes:{internal_order_id:internalId,email:customer.email}});await PaymentSession.create({internalId,razorpayOrderId:rp.id,amountPaise:rp.amount,subtotal:priced.subtotal,delivery:priced.delivery,total:priced.total,customer,address:customer.address,items:priced.items});res.json({success:true,keyId:RAZORPAY_KEY_ID,internalId,razorpayOrderId:rp.id,amount:rp.amount,currency:'INR',total:priced.total})}catch(error){res.status(error.statusCode||500).json({success:false,message:error.message})}});
app.post('/launch/payment/verify',async(req,res)=>{try{const internalId=String(req.body.internalId||''),razorpayOrderId=String(req.body.razorpay_order_id||''),paymentId=String(req.body.razorpay_payment_id||''),signature=String(req.body.razorpay_signature||''),session=await PaymentSession.findOne({internalId});if(!session)return res.status(404).json({success:false,message:'Payment session not found.'});if(session.status==='Paid'){const existing=await Order.findOne({id:internalId});return res.json({success:true,order:existing,duplicate:true})}if(razorpayOrderId!==session.razorpayOrderId)return res.status(400).json({success:false,message:'Payment order mismatch.'});const expected=crypto.createHmac('sha256',RAZORPAY_KEY_SECRET).update(`${session.razorpayOrderId}|${paymentId}`).digest('hex');if(!safeEqualText(expected,signature))return res.status(400).json({success:false,message:'Payment signature verification failed.'});session.status='Paid';session.paymentId=paymentId;session.signature=signature;session.updatedAt=new Date();await session.save();let order=await Order.findOne({id:internalId});if(!order)order=await Order.create({id:internalId,customerName:session.customer.customerName,phone:session.customer.phone,email:session.customer.email,subtotal:session.subtotal,discount:0,delivery:session.delivery,price:session.total,paymentMethod:'Razorpay',paymentStatus:'Paid',status:'Confirmed',address:session.address,items:session.items});const email=await sendEmail(order.email,`RIVAYAT payment received: ${order.id}`,orderEmail(order,'Payment received. Order confirmed.','Your payment was verified successfully. We are preparing your order.'));res.json({success:true,order,email})}catch(error){res.status(error.statusCode||500).json({success:false,message:error.message})}});
app.patch('/launch/orders/:id/status-v2',async(req,res)=>{if(!adminOnly(req,res))return;try{const status=String(req.body.status||'');if(!ORDER_STATUSES.includes(status))return res.status(400).json({success:false,message:'Invalid order status.'});const order=await Order.findOne({id:req.params.id});if(!order)return res.status(404).json({success:false,message:'Order not found.'});const changed=order.status!==status;order.status=status;order.updatedAt=new Date();await order.save();const email=changed&&order.email?await sendEmail(order.email,`RIVAYAT order ${order.id}: ${status}`,orderEmail(order,status==='Cancelled'?'Order cancelled.':`Order ${status.toLowerCase()}.`,status==='Cancelled'?'Your order has been cancelled. Contact support if you did not request this.':'Your order status has changed. You can also track it from your account.')):{skipped:true};res.json({success:true,order,email})}catch(error){res.status(500).json({success:false,message:error.message})}});
app.get('/launch/reviews/product/:productId',async(req,res)=>{try{const reviews=await ProductReview.find({productId:req.params.productId,status:'Approved'}).sort({createdAt:-1}).limit(100),count=reviews.length,average=count?reviews.reduce((s,r)=>s+Number(r.rating||0),0)/count:0;res.json({success:true,reviews,summary:{count,average:Number(average.toFixed(1))}})}catch(error){res.status(500).json({success:false,message:error.message})}});
app.post('/launch/reviews',async(req,res)=>{try{const auth=authContext(req),email=normalizeEmail(auth.email);if(!email)return res.status(401).json({success:false,message:'Sign in to review a product.'});const user=await User.findOne({email,emailVerified:true});if(!user)return res.status(403).json({success:false,message:'Verify your email before reviewing.'});const productId=String(req.body.productId||''),product=await Product.findOne({id:productId,active:{$ne:false}});if(!product)return res.status(404).json({success:false,message:'Product not found.'});const rating=Number(req.body.rating||0),text=String(req.body.text||'').trim().slice(0,2000),title=String(req.body.title||'').trim().slice(0,120);if(rating<1||rating>5||text.length<10)return res.status(400).json({success:false,message:'Choose 1–5 stars and write at least 10 characters.'});const delivered=await Order.exists({email,status:'Delivered',$or:[{'items.id':productId},{'items.productId':productId}]}),id=`pr-${Date.now()}-${crypto.randomInt(100,999)}`,review=await ProductReview.findOneAndUpdate({productId,reviewerEmail:email},{$set:{id,productId,reviewerEmail:email,reviewerName:user.name||'Customer',rating,title,text,verifiedPurchase:Boolean(delivered),status:'Pending',updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},{upsert:true,new:true});res.json({success:true,review,message:'Review submitted for moderation.'})}catch(error){if(error?.code===11000)return res.status(409).json({success:false,message:'You already reviewed this product.'});res.status(500).json({success:false,message:error.message})}});
app.get('/launch/admin/reviews',async(req,res)=>{if(!adminOnly(req,res))return;res.json({success:true,reviews:await ProductReview.find().sort({createdAt:-1}).limit(500)})});
app.patch('/launch/admin/reviews/:id',async(req,res)=>{if(!adminOnly(req,res))return;const status=String(req.body.status||'');if(!['Pending','Approved','Rejected'].includes(status))return res.status(400).json({success:false,message:'Invalid review status.'});const review=await ProductReview.findOneAndUpdate({id:req.params.id},{status,updatedAt:new Date()},{new:true});if(!review)return res.status(404).json({success:false,message:'Review not found.'});res.json({success:true,review})});
const DEFAULT_TEAM=[{name:'Shashvat Shukla',role:'Founder',initials:'SS',note:'Founder and product direction.'},{name:'Swastik Shukla',role:'Manager',initials:'SS',note:'Management and development.'},{name:'Navneet Tiwari',role:'Operations Head',initials:'NT',note:'Operations and fulfilment.'},{name:'Shantanu Shukla',role:'Business Team',initials:'ST',note:'Business and brand support.'}];
app.get('/launch/about',async(req,res)=>{try{const setting=await SiteSetting.findOne({key:'about-team'});res.json({success:true,team:Array.isArray(setting?.value?.team)&&setting.value.team.length?setting.value.team:DEFAULT_TEAM})}catch(error){res.status(500).json({success:false,message:error.message})}});
app.put('/launch/about',async(req,res)=>{if(!adminOnly(req,res))return;const team=Array.isArray(req.body.team)?req.body.team.slice(0,12).map(p=>({name:String(p.name||'').trim().slice(0,100),role:String(p.role||'').trim().slice(0,100),initials:String(p.initials||'').trim().slice(0,4),note:String(p.note||'').trim().slice(0,300)})).filter(p=>p.name):[],setting=await SiteSetting.findOneAndUpdate({key:'about-team'},{$set:{key:'about-team',value:{team},updatedAt:new Date()}},{upsert:true,new:true});res.json({success:true,team:setting.value.team})});
