(() => {
  const ORIGIN='https://rivayat.shop';
  function ensureMeta(name,attr='name'){let el=document.head.querySelector(`meta[${attr}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,name);document.head.appendChild(el)}return el}
  function setMeta(name,value,attr='name'){ensureMeta(name,attr).setAttribute('content',value)}
  function canonical(url){let el=document.head.querySelector('link[rel="canonical"]');if(!el){el=document.createElement('link');el.rel='canonical';document.head.appendChild(el)}el.href=url}
  function seoRoute(){try{return routeInfo()}catch{return{path:'/',params:new URLSearchParams()}}}
  function cleanUrl(path,params){const q=params?.toString();return ORIGIN+(path==='/'?'/':path)+(q?'?'+q:'')}
  function jsonLd(id,data){let el=document.getElementById(id);if(!el){el=document.createElement('script');el.type='application/ld+json';el.id=id;document.head.appendChild(el)}el.textContent=JSON.stringify(data)}
  function removeLd(id){document.getElementById(id)?.remove()}
  function applySeo(){const {path,params}=seoRoute();let title='RIVAYAT® Streetwear India — Hoodies, Cargos, Jackets & Shirts',description='Shop RIVAYAT streetwear in India: limited hoodies, cargos, jackets and shirts with clear product details, secure checkout, order tracking and customer support.',url=cleanUrl(path,params);
    if(path==='/about'){title='About RIVAYAT — People, Story & Streetwear Brand';description='Meet the people behind RIVAYAT and learn how the Indian streetwear project combines product identity, technology and customer trust.'}
    else if(path==='/shop'){const cat=params.get('cat');title=`${cat||'Shop'} Streetwear — RIVAYAT`;description=`Explore ${cat?cat.toLowerCase():'RIVAYAT streetwear'} with product details, sizes, stock and secure checkout.`}
    else if(path.startsWith('/product/')){const p=typeof findP==='function'?findP(decodeURIComponent(path.slice(9))):null;if(p){title=`${p.name} — RIVAYAT`;description=p.description||`Shop ${p.name} from RIVAYAT.`;url=`${ORIGIN}/product/${encodeURIComponent(p.slug||p.id)}`;jsonLd('rivayat-product-schema',{'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description||'',image:[p.image,...(p.gallery||[])].filter(Boolean).map(x=>x.startsWith('http')?x:ORIGIN+x),sku:p.id,brand:{'@type':'Brand',name:'RIVAYAT'},color:p.color||undefined,offers:{'@type':'Offer',url,priceCurrency:'INR',price:Number(p.price||0),availability:Object.values(p.inventory||{}).some(n=>Number(n)>0)?'https://schema.org/InStock':'https://schema.org/OutOfStock',itemCondition:'https://schema.org/NewCondition'},aggregateRating:Number(p.rating)>0?{'@type':'AggregateRating',ratingValue:Number(p.rating),reviewCount:Math.max(1,Number(p.reviews||1))}:undefined})}}else removeLd('rivayat-product-schema');
    if(['/privacy','/terms','/returns-policy','/shipping','/cookies'].includes(path)){const label={'/privacy':'Privacy Policy','/terms':'Terms & Conditions','/returns-policy':'Returns & Refunds','/shipping':'Shipping Policy','/cookies':'Cookies & Local Storage'}[path];title=`${label} — RIVAYAT`;description=`Read RIVAYAT ${label.toLowerCase()} and customer information.`}
    document.title=title;setMeta('description',description);setMeta('og:title',title,'property');setMeta('og:description',description,'property');setMeta('og:url',url,'property');setMeta('twitter:title',title);setMeta('twitter:description',description);canonical(url);
  }
  jsonLd('rivayat-org-schema',{'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':ORIGIN+'/#organization',name:'RIVAYAT',url:ORIGIN+'/',email:'mailto:houseofrivayat@gmail.com',sameAs:['https://www.instagram.com/houseofrivayat/','https://github.com/shashvatshukla-coder']},{'@type':'WebSite','@id':ORIGIN+'/#website',url:ORIGIN+'/',name:'RIVAYAT',publisher:{'@id':ORIGIN+'/#organization'},potentialAction:{'@type':'SearchAction',target:ORIGIN+'/#/shop?search={search_term_string}','query-input':'required name=search_term_string'}}]});
  window.addEventListener('hashchange',()=>setTimeout(applySeo,30));window.addEventListener('popstate',()=>setTimeout(applySeo,30));setTimeout(applySeo,120);
})();
